# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Anna Tomka
tagline:          'Web Developer'
description:      'This is a description'
url:              http://annatomka.github.io

author:
  name:           'Anna Tomka'
  url:            https://twitter.com/anna_tomka

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/annatomka
