# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Anna Tomka
tagline:             'Web Developer'
description:         'This is a simple blog presenting short entries about web development.'
url:                 http://annatomka.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anna Tomka
  url:               https://twitter.com/anna_tomka
  email:             tomkaanna@gmail.com

# Custom vars
version:             1.1.0

#Sitemap
gems:
  - jekyll-sitemap
