# Site settings
title: Anna Tomka 
email: tomkaanna@gmail.com
description: > # Web developer site with all the good stuff like Javascript,AngularJS,Ionic etc. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://annatomka.github.io" # the base hostname & protocol for your site
twitter_username: anna_tomka
github_username:  annatomka

# Build settings
markdown: kramdown
